# Taller 2b

Nombre: Josue Steven Calvopiña Machuca

Grado: 1CC

Fecha: 13/01/2026

**1. Para encontrar la matriz inversa de las siguientes matrices:**


In [2]:
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

import numpy as np

[01-13 17:05:44][INFO] 2026-01-13 17:05:44.370143


In [11]:
# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de eliminación gaussiana.

    ## Parameters

    ``A``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype = float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        #for j in range(i + 1, n): Eliminacion Gaussiana
        for j in range(0, n):
            if j == i:
                continue
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    """""
    # --- Sustitución hacia atrás   
    solucion = np.zeros(n)
    solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = (A[i, n] - suma) / A[i, i]
    """
    return A



$$
A_1 = \begin{bmatrix}
1 & 3 & 4 \\
2 & 1 & 3 \\
4 & 2 & 1
\end{bmatrix}
$$



In [25]:
Ab = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]
n = len(Ab)
Ag=np.hstack((Ab,np.eye(n)))
_m_ = gauss_jordan(Ag)

[01-13 17:27:00][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 17:27:00][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [ 0.  -5.  -5.  -2.   1.   0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 17:27:00][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [ 0.  -5.   0.  -2.   3.  -1. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]


In [26]:
_m_[:,n:]

array([[-0.2,  0.2,  0.2],
       [-2. ,  3. , -1. ],
       [ 0. , -2. ,  1. ]])

$$
A_2 = \begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0
\end{bmatrix}
$$



In [27]:
Ab = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
n = len(Ab)
Ag=np.hstack((Ab,np.eye(n)))
_m_ = gauss_jordan(Ag)

[01-13 17:27:22][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 17:27:22][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 17:27:22][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


In [28]:
_m_[:,n:]

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

$$
A_3 = \begin{bmatrix}
4 & 2 & 1 \\
2 & 1 & 3 \\
1 & 3 & 4
\end{bmatrix}
$$



In [23]:
Ab = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]
n = len(Ab)
Ag=np.hstack((Ab,np.eye(n)))
_m_ = gauss_jordan(Ag)

[01-13 17:26:23][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 17:26:23][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [ 0.  -5.  -5.   0.   1.  -2. ]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 17:26:23][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [ 0.  -5.   0.  -1.   3.  -2. ]
 [ 0.   0.  -5.   1.  -2.   0. ]]


In [24]:
_m_[:,n:]

array([[ 0.2,  0.2, -0.2],
       [-1. ,  3. , -2. ],
       [ 1. , -2. ,  0. ]])

$$
A_4 = \begin{bmatrix}
2 & 4 & 6 & 1 \\
4 & 7 & 5 & -6 \\
2 & 5 & 18 & 10 \\
6 & 12 & 38 & 16
\end{bmatrix}
$$

In [21]:
Ab = [[2, 4, 6, 1], [4, 7, 5, -6], [2, 5, 18, 10], [6, 12, 38, 16]]
n = len(Ab)
Ag=np.hstack((Ab,np.eye(n)))
_m_=gauss_jordan(Ag)

[01-13 17:25:57][INFO] 
[[ 2.  4.  6.  1.  1.  0.  0.  0.]
 [ 0. -1. -7. -8. -2.  1.  0.  0.]
 [ 0.  1. 12.  9. -1.  0.  1.  0.]
 [ 0.  0. 20. 13. -3.  0.  0.  1.]]
[01-13 17:25:57][INFO] 
[[  2.   0. -22. -31.  -7.   4.   0.   0.]
 [  0.  -1.  -7.  -8.  -2.   1.   0.   0.]
 [  0.   0.   5.   1.  -3.   1.   1.   0.]
 [  0.   0.  20.  13.  -3.   0.   0.   1.]]
[01-13 17:25:57][INFO] 
[[  2.    0.    0.  -26.6 -20.2   8.4   4.4   0. ]
 [  0.   -1.    0.   -6.6  -6.2   2.4   1.4   0. ]
 [  0.    0.    5.    1.   -3.    1.    1.    0. ]
 [  0.    0.    0.    9.    9.   -4.   -4.    1. ]]
[01-13 17:25:57][INFO] 
[[ 2.          0.          0.          0.          6.4        -3.42222222
  -7.42222222  2.95555556]
 [ 0.         -1.          0.          0.          0.4        -0.53333333
  -1.53333333  0.73333333]
 [ 0.          0.          5.          0.         -4.          1.44444444
   1.44444444 -0.11111111]
 [ 0.          0.          0.          9.          9.         -4.
  -4.          1

In [22]:
_m_[:,n:]

array([[ 6.4       , -3.42222222, -7.42222222,  2.95555556],
       [ 0.4       , -0.53333333, -1.53333333,  0.73333333],
       [-4.        ,  1.44444444,  1.44444444, -0.11111111],
       [ 9.        , -4.        , -4.        ,  1.        ]])

**1. Calcule la descomposición LU para estas matrices y encuentre la solución para estos vectores de valores independientes $b$.**


$$
b_1 = \begin{bmatrix}
1 \\
2 \\
4
\end{bmatrix}
$$

In [29]:
from src import descomposicion_LU,resolver_LU

In [ ]:
Ab = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

L,U = descomposicion_LU(Ab)

print(L)


[01-13 17:40:58][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 17:40:58][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:40:58][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]


In [32]:
b1 = [1, 2, 4]

resolver_LU(L, U, b1)

[01-13 17:45:11][INFO] Sustitución hacia adelante
[01-13 17:45:11][INFO] y = 
[[1.]
 [0.]
 [0.]]
[01-13 17:45:11][INFO] Sustitución hacia atrás
[01-13 17:45:11][INFO] i = 1
[01-13 17:45:11][INFO] suma = [0.]
[01-13 17:45:11][INFO] U[i, i] = -5.0
[01-13 17:45:11][INFO] y[i] = [0.]
[01-13 17:45:11][INFO] i = 0
[01-13 17:45:11][INFO] suma = [0.]
[01-13 17:45:11][INFO] U[i, i] = 1.0
[01-13 17:45:11][INFO] y[i] = [1.]


array([[ 1.],
       [-0.],
       [-0.]])

$$
b_2 = \begin{bmatrix}
3 \\
-5 \\
2
\end{bmatrix}
$$

In [39]:
Ab = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

L,U = descomposicion_LU(Ab)

print(L)

[01-13 17:50:20][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 17:50:20][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:50:20][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]


In [40]:
b2 = [3, -5, 2]

resolver_LU(L, U, b2)

[01-13 17:50:34][INFO] Sustitución hacia adelante
[01-13 17:50:34][INFO] y = 
[[  3.]
 [ -5.]
 [-33.]]
[01-13 17:50:34][INFO] Sustitución hacia atrás
[01-13 17:50:34][INFO] i = 1
[01-13 17:50:34][INFO] suma = [-132.]
[01-13 17:50:34][INFO] U[i, i] = 1.0
[01-13 17:50:34][INFO] y[i] = [-5.]
[01-13 17:50:34][INFO] i = 0
[01-13 17:50:34][INFO] suma = [155.]
[01-13 17:50:34][INFO] U[i, i] = 1.0
[01-13 17:50:34][INFO] y[i] = [3.]


array([[-152.],
       [ 127.],
       [ -33.]])

$$
b_3 = \begin{bmatrix}
7 \\
8 \\
-1
\end{bmatrix}
$$

In [35]:
Ab = [[4, 2, 1], [2, 1, 3], [1, 3, 4]]
L,U = descomposicion_LU(Ab)

print(L)

[01-13 17:49:16][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

In [36]:
Ab = [[2, 4, 6, 1], [4, 7, 5, -6], [2, 5, 18, 10], [6, 12, 38, 16]]

L,U = descomposicion_LU(Ab)

print(L)

[01-13 17:49:34][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 17:49:34][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 17:49:34][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:49:34][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]


$$
b_1 = \begin{bmatrix}
1 \\
2 \\
4 \\
5
\end{bmatrix}
$$

In [41]:
b1 = [1, 2, 4, 5]

resolver_LU(L, U, b1)

[01-13 17:51:17][INFO] Sustitución hacia adelante
[01-13 17:51:17][INFO] y = 
[[1.]
 [2.]
 [7.]]
[01-13 17:51:17][INFO] Sustitución hacia atrás
[01-13 17:51:17][INFO] i = 1
[01-13 17:51:17][INFO] suma = [28.]
[01-13 17:51:17][INFO] U[i, i] = 1.0
[01-13 17:51:17][INFO] y[i] = [2.]
[01-13 17:51:17][INFO] i = 0
[01-13 17:51:17][INFO] suma = [-31.]
[01-13 17:51:17][INFO] U[i, i] = 1.0
[01-13 17:51:17][INFO] y[i] = [1.]


array([[ 32.],
       [-26.],
       [  7.]])

$$
b_2 = \begin{bmatrix}
3 \\
-5 \\
2 \\
6
\end{bmatrix}
$$

In [42]:
b2 = [3, -5, 2, 6]

resolver_LU(L, U, b2)

[01-13 17:51:28][INFO] Sustitución hacia adelante
[01-13 17:51:28][INFO] y = 
[[  3.]
 [ -5.]
 [-33.]]
[01-13 17:51:28][INFO] Sustitución hacia atrás
[01-13 17:51:28][INFO] i = 1
[01-13 17:51:28][INFO] suma = [-132.]
[01-13 17:51:28][INFO] U[i, i] = 1.0
[01-13 17:51:28][INFO] y[i] = [-5.]
[01-13 17:51:28][INFO] i = 0
[01-13 17:51:28][INFO] suma = [155.]
[01-13 17:51:28][INFO] U[i, i] = 1.0
[01-13 17:51:28][INFO] y[i] = [3.]


array([[-152.],
       [ 127.],
       [ -33.]])

$$
b_3 = \begin{bmatrix}
7 \\
8 \\
-1 \\
0
\end{bmatrix}
$$

In [43]:
b3 = [7, 8, -1, 0]

resolver_LU(L, U, b2)

[01-13 17:51:38][INFO] Sustitución hacia adelante
[01-13 17:51:38][INFO] y = 
[[  3.]
 [ -5.]
 [-33.]]
[01-13 17:51:38][INFO] Sustitución hacia atrás
[01-13 17:51:38][INFO] i = 1
[01-13 17:51:38][INFO] suma = [-132.]
[01-13 17:51:38][INFO] U[i, i] = 1.0
[01-13 17:51:38][INFO] y[i] = [-5.]
[01-13 17:51:38][INFO] i = 0
[01-13 17:51:38][INFO] suma = [155.]
[01-13 17:51:38][INFO] U[i, i] = 1.0
[01-13 17:51:38][INFO] y[i] = [3.]


array([[-152.],
       [ 127.],
       [ -33.]])